=== WSDOT-GIS/schemastore/src/schemas/json/arcgis-web-map-data.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "ArcGIS web map JSON format",
  "definitions": {
    "versionNumber": {
      "type": "string",
      "pattern": "^\\d+(?:\\.\\d+)*$"
    },
    "layerType": {
      "type": "string",
      "enum": [
        "ArcGISMapServiceLayer",
        "ArcGISTiledMapServiceLayer"
      ]
    },
    "baseMapLayer": {
      "properties": {
        "id": {
          "type": "string"
        },
        "layerType": {
          "type": "string"
        },
        "opacity": {

          "type": "integer"
        },
        "visibility": {

          "type": "boolean"
        },
        "url": {

          "type": "string"
        }
      }
    },
    "baseMap": {
      "properties": {
        "baseMapLayers": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/baseMapLayer"
          },
          "additionalItems": false
        },
        "title": {

          "type": "string"
        }
      }
    },
    "operationalLayer": {
      "type": "object",
      "properties": {
        "id": {

          "type": "string"
        },
        "layerType": {
          "$ref": "#/definitions/layerType"
        },
        "url": {

          "type": "string"
        },
        "visibility": {

          "type": "boolean"
        },
        "opacity": {

          "type": "number",
          "minimum": 0,
          "maximum": 1
        },
        "title": {

          "type": "string"
        },
        "itemId": {

          "type": "string",
          "pattern": "^[0-9a-fA-F]+$"
        }
      }
    }
  },

  "type": "object",
  "properties": {
    "operationalLayers": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/operationalLayer"
      }
    },
    "baseMap": {
      "$ref": "#/definitions/baseMap"
    },
    "spatialReference": {
      "$ref": "arcgis-geometry.json#/definitions/spatialReference"
    },
    "authoringApp": {
      "type": "string"
    },
    "authoringAppVersion": {
      "$ref": "#/definitions/versionNumber"
    },
    "version": {
      "$ref": "#/definitions/versionNumber"
    }
  }
}

=== WSDOT-GIS/schemastore/src/test/arcgis-web-map-data/itemdata.json
{
  "operationalLayers": [
    {
      "id": "CountyBoundaries",
      "layerType": "ArcGISTiledMapServiceLayer",
      "url": "http://www.wsdot.wa.gov/geosvcs/ArcGIS/rest/services/Shared/CountyBoundaries/MapServer",
      "visibility": false,
      "opacity": 1,
      "title": "County Boundaries",
      "itemId": "fe229f9df5aa4289b8ccd2a99289951b"
    },
    {
      "id": "LegislativeDistricts",
      "layerType": "ArcGISMapServiceLayer",
      "url": "http://www.wsdot.wa.gov/geosvcs/ArcGIS/rest/services/Shared/LegislativeDistricts/MapServer",
      "visibility": false,
      "opacity": 1,
      "title": "Legislative Districts",
      "itemId": "f6d17366bae34d5f996386c2d46263ec"
    },
    {
      "id": "CityLimits",
      "layerType": "ArcGISTiledMapServiceLayer",
      "url": "http://www.wsdot.wa.gov/geosvcs/ArcGIS/rest/services/Shared/CityLimits/MapServer",
      "visibility": false,
      "opacity": 1,
      "title": "City Limits",
      "itemId": "bb7c67c334be494c88cf00ebb91fe51f"
    },
    {
      "id": "RegionalTransportationPlanning",
      "layerType": "ArcGISMapServiceLayer",
      "url": "http://www.wsdot.wa.gov/geosvcs/ArcGIS/rest/services/Shared/RegionalTransportationPlanning/MapServer",
      "visibility": false,
      "opacity": 1,
      "title": "Regional Transportation Planning Organization",
      "itemId": "d1de4f2d8a8348e0af97c858c7cff8ad"
    },
    {
      "id": "RegionBoundaries",
      "layerType": "ArcGISTiledMapServiceLayer",
      "url": "http://www.wsdot.wa.gov/geosvcs/ArcGIS/rest/services/Shared/RegionBoundaries/MapServer",
      "visibility": false,
      "opacity": 1,
      "title": "Region Boundaries",
      "itemId": "1c0845bd12944017b3bb3631bda09e0e"
    },
    {
      "id": "SixYearPlan",
      "layerType": "ArcGISMapServiceLayer",
      "url": "http://hqolymgis98d:6080/arcgis/rest/services/TransportationProjects/SixYearPlan/MapServer",
      "visibility": true,
      "opacity": 1,
      "title": "WSDOT Projects (Six Year Plan)",
      "layers": [
        {
          "id": 0,
          "popupInfo": {
            "title": "WSDOT Projects (6 Year Plan): {PIN}",
            "fieldInfos": [
              {
                "fieldName": "OBJECTID",
                "label": "OBJECTID",
                "tooltip": "",
                "visible": false,
                "format": null,
                "stringFieldOption": "textbox"
              },
              {
                "fieldName": "Region",
                "label": "Region",
                "tooltip": "",
                "visible": true,
                "format": null,
                "stringFieldOption": "textbox"
              },
              {
                "fieldName": "PIN",
                "label": "Project Number",
                "tooltip": "",
                "visible": true,
                "format": null,
                "stringFieldOption": "textbox"
              },
              {
                "fieldName": "Project_Title",
                "label": "Project Title",
                "tooltip": "",
                "visible": true,
                "format": null,
                "stringFieldOption": "textbox"
              },
              {
                "fieldName": "Improvement_Type",
                "label": "Improvement Type",
                "tooltip": "",
                "visible": true,
                "format": null,
                "stringFieldOption": "textbox"
              },
              {
                "fieldName": "Program",
                "label": "Program",
                "tooltip": "",
                "visible": true,
                "format": null,
                "stringFieldOption": "textbox"
              },
              {
                "fieldName": "Sub_Program",
                "label": "Sub Program",
                "tooltip": "",
                "visible": true,
                "format": null,
                "stringFieldOption": "textbox"
              },
              {
                "fieldName": "Work_Description",
                "label": "Work Description",
                "tooltip": "",
                "visible": true,
                "format": null,
                "stringFieldOption": "textbox"
              },
              {
                "fieldName": "PE_Start_Date",
                "label": "Preliminary Engineering Start",
                "tooltip": "",
                "visible": true,
                "format": null,
                "stringFieldOption": "textbox"
              },
              {
                "fieldName": "Ad_date",
                "label": "Advertisement",
                "tooltip": "",
                "visible": true,
                "format": null,
                "stringFieldOption": "textbox"
              },
              {
                "fieldName": "OC_Date",
                "label": "Operationally Complete",
                "tooltip": "",
                "visible": true,
                "format": null,
                "stringFieldOption": "textbox"
              },
              {
                "fieldName": "Revenue_Package",
                "label": "Revenue Package",
                "tooltip": "",
                "visible": true,
                "format": null,
                "stringFieldOption": "textbox"
              },
              {
                "fieldName": "Funding_Source",
                "label": "Funding Source",
                "tooltip": "",
                "visible": true,
                "format": null,
                "stringFieldOption": "textbox"
              },
              {
                "fieldName": "Congressional_District",
                "label": "Congressional District",
                "tooltip": "",
                "visible": true,
                "format": null,
                "stringFieldOption": "textbox"
              },
              {
                "fieldName": "Legislative_District",
                "label": "Legislative District",
                "tooltip": "",
                "visible": true,
                "format": null,
                "stringFieldOption": "textbox"
              },
              {
                "fieldName": "County",
                "label": "County",
                "tooltip": "",
                "visible": true,
                "format": null,
                "stringFieldOption": "textbox"
              },
              {
                "fieldName": "Route",
                "label": "Route",
                "tooltip": "",
                "visible": true,
                "format": null,
                "stringFieldOption": "textbox"
              },
              {
                "fieldName": "Begin_Mile_Post",
                "label": "Begin Mile Post",
                "tooltip": "",
                "visible": true,
                "format": {
                  "places": 2,
                  "digitSeparator": true
                },
                "stringFieldOption": "textbox"
              },
              {
                "fieldName": "End_Mile_Post",
                "label": "End Mile Post",
                "tooltip": "",
                "visible": true,
                "format": {
                  "places": 2,
                  "digitSeparator": true
                },
                "stringFieldOption": "textbox"
              },
              {
                "fieldName": "Shape",
                "label": "Shape",
                "tooltip": "",
                "visible": false,
                "format": null,
                "stringFieldOption": "textbox"
              },
              {
                "fieldName": "LRS_Date",
                "label": "SRMP Date",
                "tooltip": "",
                "visible": true,
                "format": null,
                "stringFieldOption": "textbox"
              }
            ],
            "description": null,
            "showAttachments": true,
            "mediaInfos": []
          }
        }
      ]
    },
    {
      "id": "MilepostValues",
      "layerType": "ArcGISMapServiceLayer",
      "url": "http://wsdot.wa.gov/geosvcs/ArcGIS/rest/services/Shared/MilepostValues/MapServer",
      "visibility": false,
      "opacity": 1,
      "title": "Milepost Values",
      "itemId": "03ec5ff3609f45caa849d5afa4d92e9e"
    }
  ],
  "baseMap": {
    "baseMapLayers": [
      {
        "id": "wsdotbasemap",
        "layerType": "ArcGISTiledMapServiceLayer",
        "opacity": 1,
        "visibility": true,
        "url": "http://www.wsdot.wa.gov/geosvcs/ArcGIS/rest/services/Shared/WebBaseMapWebMercator/MapServer"
      }
    ],
    "title": "WSDOT Basemap"
  },
  "spatialReference": {
    "wkid": 102100,
    "latestWkid": 3857
  },
  "authoringApp": "WebMapViewer",
  "authoringAppVersion": "3.10",
  "version": "2.3"
}
